export const ISO27001_CONTROLS = [
    // Organizational
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.1", title: "Policies for information security" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.2", title: "Information security roles and responsibilities" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.3", title: "Segregation of duties" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.4", title: "Management responsibilities" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.5", title: "Contact with authorities" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.6", title: "Contact with special interest groups" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.7", title: "Threat intelligence" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.8", title: "Information security in project management" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.9", title: "Inventory of information and other associated assets" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.10", title: "Acceptable use of information and other associated assets" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.11", title: "Return of assets" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.12", title: "Classification of information" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.13", title: "Labelling of information" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.14", title: "Information transfer" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.15", title: "Access control" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.16", title: "Identity management" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.17", title: "Authentication information" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.18", title: "Access rights" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.19", title: "Information security in supplier relationships" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.20", title: "Addressing information security within supplier agreements" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.21", title: "Managing information security in the ICT supply chain" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.22", title: "Monitoring, review and change management of supplier services" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.23", title: "Information security for use of cloud services" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.24", title: "Information security incident management planning and preparation" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.25", title: "Assessment and decision on information security events" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.26", title: "Response to information security incidents" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.27", title: "Learning from information security incidents" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.28", title: "Collection of evidence" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.29", title: "Information security during disruption" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.30", title: "ICT readiness for business continuity" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.31", title: "Legal, statutory, regulatory and contractual requirements" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.32", title: "Intellectual property rights" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.33", title: "Protection of records" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.34", title: "Privacy and protection of PII" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.35", title: "Independent review of information security" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.36", title: "Compliance with policies, rules and standards for information security" },
    { standard: "ISO 27001:2022", domain: "Organizational", clause: "Annex A", control: "A.5.37", title: "Documented operating procedures" },
  
    // People
    { standard: "ISO 27001:2022", domain: "People", clause: "Annex A", control: "A.6.1", title: "Screening" },
    { standard: "ISO 27001:2022", domain: "People", clause: "Annex A", control: "A.6.2", title: "Terms and conditions of employment" },
    { standard: "ISO 27001:2022", domain: "People", clause: "Annex A", control: "A.6.3", title: "Information security awareness, education and training" },
    { standard: "ISO 27001:2022", domain: "People", clause: "Annex A", control: "A.6.4", title: "Disciplinary process" },
    { standard: "ISO 27001:2022", domain: "People", clause: "Annex A", control: "A.6.5", title: "Responsibilities after termination or change of employment" },
    { standard: "ISO 27001:2022", domain: "People", clause: "Annex A", control: "A.6.6", title: "Confidentiality or non-disclosure agreements" },
    { standard: "ISO 27001:2022", domain: "People", clause: "Annex A", control: "A.6.7", title: "Remote working" },
    { standard: "ISO 27001:2022", domain: "People", clause: "Annex A", control: "A.6.8", title: "Information security event reporting" },
  
    // Physical
    { standard: "ISO 27001:2022", domain: "Physical", clause: "Annex A", control: "A.7.1", title: "Physical security perimeters" },
    { standard: "ISO 27001:2022", domain: "Physical", clause: "Annex A", control: "A.7.2", title: "Physical entry" },
    { standard: "ISO 27001:2022", domain: "Physical", clause: "Annex A", control: "A.7.3", title: "Securing offices, rooms and facilities" },
    { standard: "ISO 27001:2022", domain: "Physical", clause: "Annex A", control: "A.7.4", title: "Physical security monitoring" },
    { standard: "ISO 27001:2022", domain: "Physical", clause: "Annex A", control: "A.7.5", title: "Protecting against physical and environmental threats" },
    { standard: "ISO 27001:2022", domain: "Physical", clause: "Annex A", control: "A.7.6", title: "Working in secure areas" },
    { standard: "ISO 27001:2022", domain: "Physical", clause: "Annex A", control: "A.7.7", title: "Clear desk and clear screen" },
    { standard: "ISO 27001:2022", domain: "Physical", clause: "Annex A", control: "A.7.8", title: "Equipment siting and protection" },
    { standard: "ISO 27001:2022", domain: "Physical", clause: "Annex A", control: "A.7.9", title: "Security of assets off-premises" },
    { standard: "ISO 27001:2022", domain: "Physical", clause: "Annex A", control: "A.7.10", title: "Storage media" },
    { standard: "ISO 27001:2022", domain: "Physical", clause: "Annex A", control: "A.7.11", title: "Supporting utilities" },
    { standard: "ISO 27001:2022", domain: "Physical", clause: "Annex A", control: "A.7.12", title: "Cabling security" },
    { standard: "ISO 27001:2022", domain: "Physical", clause: "Annex A", control: "A.7.13", title: "Equipment maintenance" },
    { standard: "ISO 27001:2022", domain: "Physical", clause: "Annex A", control: "A.7.14", title: "Secure disposal or re-use of equipment" },
  
    // Technological
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.1", title: "User endpoint devices" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.2", title: "Privileged access rights" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.3", title: "Information access restriction" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.4", title: "Access to source code" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.5", title: "Secure authentication" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.6", title: "Capacity management" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.7", title: "Protection against malware" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.8", title: "Management of technical vulnerabilities" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.9", title: "Configuration management" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.10", title: "Information deletion" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.11", title: "Data masking" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.12", title: "Data leakage prevention" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.13", title: "Information backup" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.14", title: "Redundancy of information processing facilities" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.15", title: "Logging" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.16", title: "Monitoring activities" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.17", title: "Clock synchronization" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.18", title: "Use of privileged utility programs" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.19", title: "Installation of software on operational systems" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.20", title: "Networks security" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.21", title: "Security of network services" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.22", title: "Segregation of networks" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.23", title: "Web filtering" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.24", title: "Use of cryptography" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.25", title: "Secure development life cycle" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.26", title: "Application security requirements" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.27", title: "Secure system architecture and engineering principles" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.28", title: "Secure coding" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.29", title: "Security testing in development and acceptance" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.30", title: "Outsourced development" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.31", title: "Separation of development, test and production environments" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.32", title: "Change management" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.33", title: "Test information" },
    { standard: "ISO 27001:2022", domain: "Technological", clause: "Annex A", control: "A.8.34", title: "Protection of information systems during audit testing" },
  ];